version: '3'

# Thoses tasks allow to run GithubActions


tasks:

  merge_develop_into_master:
    cmds:
      - git checkout main
      - git pull origin
      - git fetch origin develop:develop
      - 'git merge --no-ff -m "chore: merge develop into main" develop'
      - git push --set-upstream origin main

  merge_master_into_develop:
    cmds:
      - git checkout develop
      - git pull origin
      - git fetch origin main:main
      - 'git merge --no-ff -m "chore: update develop from main" main'
      - git push --set-upstream origin develop

  release_stable:
    desc: Pipeline to run to apply
    vars:
      CURRENT_BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
    cmds:
      - task: merge_develop_into_master
      - task release_stable
      - task: merge_master_into_develop


  release_beta:
    desc: Pipeline to run to apply
    vars:
      CURRENT_BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
    cmds:
      - task release_beta


 #     - git checkout main
 #     - git pull origin

 #     - git fetch origin develop:develop
 #     - 'git merge --no-ff -m "chore: merge develop into main" develop'

 #     - semantic-release -D tag_commit=true publish
 #     - git push origin

 #     - git checkout develop
 #     - 'git merge --no-ff -m "chore: update develop from main" main'
 #     - git push --set-upstream origin develop

 #     - |2
 #       if [[ "{{.CURRENT_BRANCH}}" == main ]]; then
 #         git checkout $CURR_BRANCH
 #       fi
