version: '3'

# See guidelines: https://github.com/dxw/scripts-to-rule-them-all

# Vars: Example
#   GIT_TAG:
#     sh: git describe --tags 2>/dev/null || echo devel
#   GIT_BRANCH:
#     sh: git rev-parse --abbrev-ref HEAD
#   PRJ_VERSION:
#     sh: poetry version -s


vars:
  SRC_DIR: myprj
  TEST_DIR: tests/


includes:
  #doc:
  #  taskfile: ./docs/Taskfile.yml
  #  dir: ./docs

  #gh:
  #  taskfile: ./.github/Taskfile.yml
  #  dir: .
    #internal: true

  dev:
    taskfile: ./scripts/Taskfile.yml
    dir: .
  docker:
    taskfile: ./docker/Taskfile.yml


tasks:

  # Generic helpers
  # -----------------

  default:
    desc: Show all commands
    cmds:
      - task --list-all

  # Project helpers
  # -----------------

  bootstrap:
    desc: Bootstrap environment
    sources:
      - poetry.lock
    cmds:
      - poetry config --list
      - poetry install -vv --no-interaction --no-root

  setup:
    desc: Setup project
    cmds:
      - poetry install -vv --no-interaction --only-root

  update:
    desc: Synchronize git
    cmds:
      - git fetch -a && git pull


  # Build workflow
  # -----------------

  build_changelog:
    desc: "Used by semantic-release during publish process, as pre-commit command"
    internal: true
    cmds:
      - poetry run semantic-release changelog --unreleased > VERSION_NOTES.md

  build:
    desc: Create a python package
    # Used by semantic-release during publish process, as pre-commit command
    deps:
      - clean
    cmds:
      - poetry build
      - cp CHANGELOG.md dist/CHANGELOG.md
      - cp VERSION_NOTES.md dist/RELEASE.md

  clean:
    desc: Clean generated packages
    cmds:
      - rm -rf dist/ && mkdir -p dist
    status:
      - test ! -d dist/


  # Release workflow
  # -----------------

  release_version:
    desc: Show release status
    cmds:
      - poetry run ./scripts/versions.sh

  release_stable:
    desc: Bump code stable version, generate changelog, create a tag
    # Note having :
    # GH_TOKEN set will create a release in github
    # PYPI_TOKEN set will release a version on pypi
    cmds:
      - |2
        if [[ "$(git rev-parse --abbrev-ref HEAD)" != main ]]; then
          echo "You must checkout main first"
          exit 1
        fi
        ! git status -s | grep -E '^[AM]* '
        # FIXME: Currently semantic-release take care of the gh upload and pypi
        # publishing, but ultimately, we would have a better control on them.
      - SKIP=end-of-file-fixer  poetry run semantic-release -D tag_commit=true publish -v DEBUG
      - task: publish_pypi
      #- task: publish_gh

  release_beta:
    aliases:
      - release
    desc: Bump code stable version, generate changelog, create a tag
    cmds:
      - |2
        if [[ "$(git rev-parse --abbrev-ref HEAD)" != develop ]]; then
          echo "You must checkout develop first"
          exit 1
        fi
        ! git status -s | grep -E '^[AM]* '
      - >
        SKIP=end-of-file-fixer poetry run semantic-release
        -D tag_commit=true
        -D branch=develop
        publish --prerelease
      - task: publish_pypi



  # Publish workflow
  # -----------------

  publish_pypi:
    desc: Publish python package on pypi.org
    deps:
      - build
      - build_changelog
    cmds:
      - poetry publish

  #publish_gh:
  #  desc: Create a python package
  #  interactive: true
  #  deps:
  #    - build_changelog
  #    - build
  #  cmds:
  #    - ls -ahl dist/
  #    - cat VERSION_NOTES.md  | ./scripts/publish_github.sh mrjk/python-project-poetry-template  -- dist/*




#
#  # Project Workflow
#  # ---------------
#  run_qa:
#    desc: Run short test suites
#    deps:
#    - run_black
#    - report_linting
#
#  run_test:
#    desc: Run full test suites
#    deps:
#    - run_black
#    - run_test
#    - report_coverage
#    - report_linting
#
#
#
#  # Top level Workflow
#  # ---------------
#
#  # serve_doc:
#  #   desc: Serve locally documentation site
#  #   deps:
#  #     - doc:serve_doc
#
#  clean:
#    desc: Clean all artifacts
#    deps:
#      - pkg_clean
#      - docker_clean
#
