version: '3'

vars:
  GIT_REF:
    sh: git rev-parse --short HEAD
  GIT_BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  APP_VERSION:
    sh: poetry version -s 2>/dev/null || true

  #GIT_TAG:
  #  sh: git describe --tags 2>/dev/null || echo devel


# See guidelines: https://github.com/dxw/scripts-to-rule-them-all

tasks:

  # Geneeric helpers
  # -----------------

  default:
    desc: Show all commands
    cmds:
      - task --list-all

  #bootstrap:
  #  desc: Bootstrap all
  #  cmds:
  #    - for c in $(task -l | grep -Eo '[^ ]+_bootstrap'); do task $c ; done

  #build:
  #  desc: Bootstrap all
  #  cmds:
  #    - for c in $(task -l | grep -Eo '[^ ]+_build'); do task $c ; done

  version_list:
    desc: List documentation versions
    cmds:
      - mike list

  # via git on branch gh_page
  publish_gh:
    desc: 'Publish documentation on: https://mrjk.github.io/python-project-poetry-template/index.html'
    vars:
      GIT_REF:
        sh: git rev-parse --short HEAD
      GIT_BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
      APP_VERSION:
        sh: poetry version -s 2>/dev/null || true
      APP_MINOR:
        sh: git describe --tags --abbrev=0 | sed -E  's/(v?[0-9]+\.([0-9]+)).*/\1/'
    cmds:
      - mike list
      - |
        MSG="Deployed {{.APP_VERSION}} - {{.GIT_REF}} from {{.GIT_BRANCH}}"
        mike deploy --push -m "$MSG" --update-aliases {{.APP_MINOR}} latest
      - mike list
      #- git push origin gh-pages:gh-pages
#      - mkdocs gh-deploy --message 'Deployed {{.APP_VERSION}} - {{.GIT_REF}} from {{.GIT_BRANCH}}'


  # MkDocs (Local Python)
  # -----------------

  doc_build:
    desc: Generate API doc
    #deps: [install]
    run: once
    cmds:
      - ./gen_apidoc.sh
    sources:
      - ../paasify/*.py

  doc_serve:
    aliases:
      - serve
    desc: Run mkdocs website
    # deps: [doc_build]
    interactive: true
    cmds:
      - >
        echo "Documentation: http://127.0.0.1:8000"
      - mkdocs serve


  # Jupyter (Local Python)
  # -----------------
  jupyter_bootstrap:
    desc: Install jupyter dependencies
    cmds:
      - python -m bash_kernel.install

  jupyter_serve:
    desc: Run jupyter playbook editor website
    interactive: true
    cmds:
      - >
        echo "Jupyter: http://127.0.0.1:8888"
      - jupyter-notebook --autoreload --notebook-dir src/jupyter/


  # Online VS-Code (docker)
  # -----------------
  docker_serve:
    alias:
      - vscode
      - edit
    desc: Run documentation IDE
    deps: [doc_build]
    cmds:
      - docker-compose up -d
      - |
        sleep 3
        echo "Documentation: http://127.0.0.1:8042"
        echo "Jupyter:       $( docker-compose logs | grep -m 1 ' or http:' | sed 's/.* or //' )"

  docker_serve_stop:
    desc: Stop documentation IDE
    cmds:
      - docker-compose rm -f
      #- docker-compose stop
